name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube scanner
        uses: actions/cache@v3
        with:
          path: C:\Sonaqube\sonar-scanner-6.1.0.4477-windows-x64\bin
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube scan
        run: |
          C:\SonarQube\sonarqube-10.6.0.92116\bin\sonar-scanner.bat -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
