name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Download SonarQube scanner
        run: |
          curl -sSLo $HOME/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip $HOME/sonar-scanner.zip -d $HOME/
          mv $HOME/sonar-scanner-4.6.2.2472-linux $HOME/sonar-scanner

      - name: Configure SonarQube Scanner
        run: |
          echo "sonar.projectKey=codeReview" > $HOME/sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.host.url=https://ccde-61-95-213-22.ngrok-free.app" >> $HOME/sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> $HOME/sonar-scanner/conf/sonar-scanner.properties
          echo "sonar.java.binaries=**/*.java" >> $HOME/sonar-scanner/conf/sonar-scanner.properties

      - name: Check Java version
        run: java -version

      - name: Run SonarQube scan
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
          PATH: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64/bin:$PATH
        run: |
          JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64 $HOME/sonar-scanner/bin/sonar-scanner -Dsonar.verbose=true

      - name: Upload scan results
        run: |
          echo "SonarQube scan completed."
